name: "codesigner"
author: "E-Signer.com"
branding:
  icon: "feather"
  color: "green"
description: ""
inputs:
  command:
    description: "Command for CodeSignTool"
    required: true
    default: "--version"
  username:
    description: "ssl.com's username"
    required: false
  password:
    description: "ssl.com's password"
    required: false
  credential_id:
    description: "eSigner credential id"
    required: false
  totp_secret:
    description: "Code Signing totp secret code"
    required: false
  program_name:
    description: ""
    required: false
  file_path:
    description: ""
    required: false
  dir_path:
    description: ""
    required: false
  output_path:
    description: ""
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.command }}
